codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "30...100"
  status:
    patch:
      default:
        target: auto
        threshold: 10%
        base: auto
    project:
      default:
        target: auto
        threshold: 5%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no